### ISSUE TITLE
"TabError: inconsistent use of tabs and spaces in indentation"

### ISSUE THREAD

**Issue by S1SYPHOS** [berteh/ScribusGenerator#139]
When running with python3, I get this error:

```text
Traceback (most recent call last):
  File "/path/to/berteh/scribusgenerator/ScribusGeneratorCLI.py", line 22, in <module>
    import ScribusGeneratorBackend
  File "/path/to/berteh/scribusgenerator/ScribusGeneratorBackend.py", line 298
    outTree.write(scribusOutputFilePath, encoding="UTF-8")
                                                         ^
TabError: inconsistent use of tabs and spaces in indentation
```

Since I'm not a python man myself, I don't know if that's suspicious or totally normal, given it's not Python 2.7+, but v3 - well, maybe it's something!

Cheers,
S1SYPHOS

**Comment by berteh** [comment]
nice catch. should be fixed now. thanks.
