### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by S1SYPHOS** [berteh/ScribusGenerator#148]
Hey there,
lately, I've been getting this:
```
Traceback (most recent call last):
  File "./vendor/berteh/scribusgenerator/ScribusGeneratorCLI.py", line 124, in <module>
    generator = ScribusGenerator(dataObject)
  File "/path/to/vendor/berteh/scribusgenerator/ScribusGeneratorBackend.py", line 74, in __init__
    os.path.abspath(os.path.dirname(__file__)), 'logging.conf'))
  File "/usr/lib64/python3.7/logging/config.py", line 79, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib64/python3.7/logging/config.py", line 145, in _install_handlers
    h = klass(*args, **kwargs)
  File "/usr/lib64/python3.7/logging/handlers.py", line 146, in __init__
    if maxBytes > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
Array
(
)
```
Any idea? I'm pretty helpless .. `logging.conf` is standard (same as your repo)

**Comment by S1SYPHOS** [comment]
nvm, was outside my virtualenv and had python3.5 running ..
