### ISSUE TITLE
except IOError as

### ISSUE THREAD

**Issue by gbuendia** [berteh/ScribusGenerator#63]
On going to Scribus > Scrips > Execute script... and opening scribusgenerator.py I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/Users/guillem/.scribus/scripts/ScribusGenerator-master/ScribusGenerator.py", line 153
     except IOError as e:   #except FileNotFoundError as e:
                     ^
 SyntaxError: invalid syntax

```
`python --version` says `Python 2.7.11`

**Comment by gbuendia** [comment]
I cannot find ~/.scribusGenerator.log

And (sorry) now I see that the error also says
`If you are running and official script report it at bugs.scribus.net please.`
Should I go there instead?

**Comment by berteh** [comment]
Hello @gbuendia 

This is the right place to report this problem, as this script is not an "official" one from the scribus core team.

What OS and version of Scribus are you using?

From your first report it looks like you're using some windows, in this case the log file should be located in C:\Users\guillem\.scribusGenerator.log    it is indeed there?, and if yes can you paste the end of it to get more information on that particular error.

**Comment by gbuendia** [comment]
Hi! Thanks for answering so quickly.

I'm on a Mac running OS X 10.9.5 (Mavericks). My Scribus version is 1.4.5.

I can confirm there's no log in ~/ after the error in Scribus. But it is created after running the CLI version (which works nice: `2016-09-23 08:30:38 - INFO - <module>:149 - Scribus Generation completed. Congrats!`).

Trying to run the script again from Scribus and getting the error does not add any lines to that log.

**Comment by berteh** [comment]
Could you please then try to remove the end of the faulty code line, in ScribusGenerator.py line 153? removing everything after the double dots: ```   #except FileNotFoundError as e:```
saving, and then trying again?

If that results in another syntax error on line 234 simply repeat the same modification to get rid of ``` # ⟲ ⟳ ↻ ↺ ⌂ ⌘ ⎗``` and you should be good to go.


That being said I don't get why you'd get a syntax error in that place... so this might need more investigations. Since the script runs fine in Ubuntu and Windows I suspect a problem with some version of the python interpreter.

Could you please check which version of python is embedded in your Scribus flavour?  You can get that info by going to ```Script > show Console```, then paste the following lines in the top box (commands): 

    import sys
    print(sys.version)

running it via ```Script > run``` and pasting the output (bottom box) here.

My result for Scribus 1.4.5 in Windows is ```2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]```

**Comment by gbuendia** [comment]
Hi. Unfortunately, removing the `#except FileNotFoundError as e:` part does not change the result.

What I get running the console command is:

```
2.5.6 (r256:Unversioned directory, Mar  9 2014, 22:15:03) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
```

I guess that shouldn't be like that, should it?

**Comment by berteh** [comment]
Well there's not much we can do to update the embedded python version (it has been defined by the guy who packaged it for Mac)... but it may be a reason for failure as 2.5.6 is quite old.

Would it be possible for you to update your Scribus to the more recent [1.5.2](https://www.scribus.net/downloads/unstable-branch/)? It's [announced by the developers](https://www.scribus.net/scribus-1-5-2-released/) as stable enough in production, and I confirm using it satisfactorily in both Windows and Ubuntu. You get added bonus of more functionnalities, but gotta be cautious as the format is not backwards compatible, so making a backup of your current sla is advised.

**Comment by gbuendia** [comment]
Just updated both things. Now I get:
```
2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
```

... But now trying to open the script gets me either a spinning cursor. I can still use Scribus but the three first elements of the Script menu are greyed out. After a while, all the contents —texts, graphics, etc— of the document appear transparent (it's just a test card like in your video tutorial, nothing important to lose) until I close and reopen it. The script menu remains grey, though.

I tried downloading your release 2.3 of august, too, but Scribus crashes. No new lines in the log.

I don't know what other info can help.

**Comment by berteh** [comment]
Prefer the current code rather than the 2.3 release (I'll make a new release when we find a fix to your problem).

I've had previous reports of the Mac version of python not always including tK interface (it's the GUI library I use).. but don't know how to check and/or fix this.

We could at least test it quickly to rule this problem in or out: could you please try to run the few scripts below from scribus (either from the console or by saving them to a standalone file and running them using ```Script > Run``` and see if you get indeed a set of 3 dialogs that displays allright?

guitest1.py

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    import tkMessageBox
    tkMessageBox.showinfo('box', message='this is a message box')      

guitest2.py

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    import tkFileDialog
    file = tkFileDialog.askopenfilename(title='Choose...', defaultextension='.csv', filetypes=[('CSV - comma separated values', '*.csv *.CSV'),('TSV - tab separated values', '*.tsv *.TSV'),('TXT - text', '*.txt *.TXT'),('all','*.*')])
    if file:
        print("file is %s"%file)
    else:
        print("no file was selected")

guitest3.py

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    import Tkinter
    from Tkinter import Frame, LabelFrame, Label, Entry, Button, StringVar, OptionMenu, Checkbutton, IntVar, DISABLED, NORMAL, PhotoImage
    Tkinter._test() # a small windows with 2 buttons should pop up. It may be located under the current application.

**Comment by gbuendia** [comment]
I did this first, both in Scribus console and in Terminal, both successfully:
```
>>> import Tkinter
>>> print Tkinter.TkVersion
8.5
```

The first test (messageBox) worked on Terminal, but caused Scribus to crash the first time, and do nothing the second (but the normal Script menu is greyed out, and trying to run the test again from the console Script menu yields: `Another script is already running... Please let it finish its task...`

I too can use the CLI version, I think it works fine; and I will need a single file output, so exporting the PDF manually will not be painful for me.

**Comment by Jamcob** [comment]
I'm getting a similar issue, running MAC OS 10.11 and Scribus 1.5.2, every time I try and run the sript I get a loading cursor and nothing else happens. Have we found a fix for this?

**Comment by berteh** [comment]
Hello.
This problem is known on Mac OSX, and due to the fact it does not ship with
some library (TKinter) needed to display the graphical interface of Scribus
Generator.

So far I found no GUI alternative available on all OSes. If you know of one
kindly let me know.

 Meanwhile the command line interface of Scribus Generator works just fine.
You can find all needed information on the project homepage, readme, and in
our wiki.

Hope this helps.
Better.

**Comment by gbuendia** [comment]
I'm no longer on MacOS so I can't try more things to help.
