### ISSUE TITLE
When I try to open scribusgenerator using "execute script" on Mac, it just freezes Scribus altogether.

### ISSUE THREAD

**Issue by ges74** [berteh/ScribusGenerator#96]
I see a spinning rainbow circle.  What am I doing wrong?  I would very much like to try your script to autopopulate newsletter content.  Thank you very much, Eileen

**Comment by ges74** [comment]
I know you asked posters to add the last few lines of their log file, but I don't even know how to get there.  Sorry. :(

**Comment by ges74** [comment]
Yes, if only I was proficient enough to understand how to operate a command line interface…sigh.
I will check out the thread you mention below - I just read it and I have no idea what anyone is talking about.  :D  I guess I also need to do research on what MacPorts is.
I will at minimum bookmark thread #104 and follow the dialogue.
Thank you for getting back to me on this.
Eileen

**Comment by berteh** [comment]
maybe this can help with the command line:
http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line
https://www.macworld.co.uk/how-to/mac-software/how-use-terminal-on-mac-3608274/

After reading the documents above, let's imagine that your SLA template and CSV data are in your folder _Documents/scribus_, and that you downloaded ScribusGenerator-master.zip from Github and uncompressed it in your folder _Downloads/ScribusGenerator-master_. You would then

1. open a Terminal
1. go to your project directory: ``cd Documents/scribus``
1. create a shortcut to SG in your project folder: ``ln -s ~/Downloads/ScribusGenerator-master/ScribusGeneratorCLI.py .``
1. check that Scribus Generator (SG, in short) works: ``./ScribusGeneratorCLI.py --outDir test Business_Card.sla``. This step should create 10 SLA files with a business card in the _Documents/scribus/test_ folder.
1. understand the available options to run SG from the command line (they are basically the same as the GUI), either [online](command) or directly from your command line:   ``./ScribusGeneratorCLI.py --help``
1. invent a command that will suit your needs, maybe something like: ````./ScribusGeneratorCLI.py --csvFile myData.csv --outDir . --merge myTemplate.sla``
1. open the generated SLA file with Scribus to enjoy the result... and generate a pdf or an image out of it.

If you want more help to create a particular command don't hesitate to give me a few more details on your particular needs.

Hope this helps,
Berteh.

**Comment by ges74** [comment]
Oh wow Berteh, thank you SO MUCH for putting in the time and energy to draft this email to me.
I generate my newsletter on a monthly basis.
I am tied up until 4/23 with travel and US tax submission (not for the fainthearted!) but if okay with you I would love to try this out after that and see how it works.
Again, thank you so much for your assistance to a clueless newbie [which in and of itself is a travesty - I see you use “the MIT license” and I went to MIT for undergraduate studies….but in Course II (Mechanical Eng’g), not Course 6-3 (computer science)!]
Eileen

**Comment by berteh** [comment]
you're more than welcome Eileen, I was a newbie once too ;)

**Comment by berteh** [comment]
and for after April 23rd I did put this documentation (and a bit more) in this project's wiki... as it may help others too: https://github.com/berteh/ScribusGenerator/wiki/Running-Scribus-Generator-from-the-command-line

**Comment by ges74** [comment]
thank you!!!  I will look at it in detail then!!!!!!

**Comment by ges74** [comment]
Berteh,
Thanks again for helping me out with this.  I have gotten through almost all of step 4 below, except I get this error when I run the script:

users-MacBook-Pro:scribus owner$ ./ScribusGeneratorCLI.py --outDir test Business_Card.sla
16:32:30 - ScribusGenerator - INFO: ScribusGenerator initialized
16:32:30 - ScribusGenerator - INFO: Generating all files for Business_Card.sla in directory test
16:32:30 - ScribusGenerator - INFO: parsing scribus source file Business_Card.sla
16:32:30 - ScribusGenerator - INFO: parsing data source file Business_Card.csv
16:32:30 - ScribusGenerator - ERROR: 
error: Traceback (most recent call last):
  File "./ScribusGeneratorCLI.py", line 148, in <module>
    generator.run()
  File "/Users/owner/Downloads/ScribusGenerator-master/ScribusGeneratorBackend.py", line 110, in run
    csvData = self.getCsvData(self.__dataObject.getDataSourceFile())
  File "/Users/owner/Downloads/ScribusGenerator-master/ScribusGeneratorBackend.py", line 481, in getCsvData
    for row in reader:
Error: line contains NULL byte

what am I doing wrong?
I’ve attached screen shots of the way my file structure is set up, plus the contents of the template and the csv file.

**Comment by rotor-head** [comment]
Just to close the loop on the MacPorts version of this discussion … it did not work.

**Comment by berteh** [comment]
just as a reference to me, pending confirmation from @ges74, looks like this particular CSV file may be an XLS, and not a real CSV, per  https://stackoverflow.com/questions/4166070/python-csv-error-line-contains-null-byte

**Comment by ges74** [comment]
Hi Berteh,
I jettisoned my newsletter responsibilities literally just 5 minutes ago so no longer have a need for the script.  I appreciate your taking the time and effort to try to help, however.
Best wishes,
Eileen
