### ISSUE TITLE
Script crushes with this error? Can you help?

### ISSUE THREAD

**Issue by mikeplum** [berteh/ScribusGenerator#97]
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Program Files (x86)\Scribus 1.4.6\share\scripts\ScribusGenerator.py", line 344, in <module>
    main_wrapper(sys.argv)
  File "C:\Program Files (x86)\Scribus 1.4.6\share\scripts\ScribusGenerator.py", line 332, in main_wrapper
    main(argv)
  File "C:\Program Files (x86)\Scribus 1.4.6\share\scripts\ScribusGenerator.py", line 321, in main
    dlg = GeneratorDialog(root, ctrl)
  File "C:\Program Files (x86)\Scribus 1.4.6\share\scripts\ScribusGenerator.py", line 200, in __init__
    self.__ico=PhotoImage(file=self.__pluginDir+'/pic/ScribusGenerator_logo.gif')
  File "C:\Program Files (x86)\Scribus 1.4.6\lib\lib-tk\Tkinter.py", line 3366, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Program Files (x86)\Scribus 1.4.6\lib\lib-tk\Tkinter.py", line 3320, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
TclError: couldn't open "C:\Program Files (x86)\Scribus 1.4.6\share\scripts/pic/ScribusGenerator_logo.gif": no such file or directory

**Comment by mikeplum** [comment]
Solved, I was need to copy "pic" folder (from dowloaded ScribusGenerator package) into directory into "...\Scribus 1.4.6\share\scripts/"

Many thanks!
