### ISSUE TITLE
Script doesn't work with Scribus1.5.3 

### ISSUE THREAD

**Issue by mikeplum** [berteh/ScribusGenerator#98]
When I try to execute Script I've recieved this stacktrace.

Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "C:\Users\xxx\Downloads\ScribusGenerator-master\ScribusGenerator.py", line 22, in <module>
    import ScribusGeneratorBackend
  File "C:\Users\xxx\Downloads\ScribusGenerator-master\ScribusGeneratorBackend.py", line 29, in <module>
    import logging.config
  File "C:\bin\Scribus 1.5.3\python\lib\logging\config.py", line 31, in <module>
    import logging.handlers
  File "C:\bin\Scribus 1.5.3\python\lib\logging\handlers.py", line 26, in <module>
    import errno, logging, socket, os, cPickle, struct, time, re
  File "C:\bin\Scribus 1.5.3\python\lib\socket.py", line 47, in <module>
    import _socket
ImportError: DLL load failed: Cannot find a specific procedure.

**Comment by mikeplum** [comment]
WALK AROUND: 

python27.dll file in version 1.5.3 is in different place relative to older stable 1.4.6 version. 

In 1.4.6 file was in the home Scribus directory, in 1.5.3 it was in 
Scribus 1.5.3\python 

I've just copy python27.dll from Scribus 1.5.3\python directory to home directory and Script starts working again.
